### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by aamershahzad2** [Ingenico-ePayments/connect-sdk-client-swift-example#1] opened 2019-01-15 13:15 UTC
App crash after payment has been successfully processed.

**Comment by LeonStemerdink** [comment] 2019-01-15 13:19
The crash is probably caused by [this issue](https://github.com/Ingenico-ePayments/connect-sdk-client-swift/issues/3) on the sdk, which should be resolved shortly.

**Comment by LeonStemerdink** [comment] 2019-01-18 10:01
The issue I referenced in my previous comment has been fixed with [release 3.2.0 of the Ingenico Connect Swift Client SDK](https://github.com/Ingenico-ePayments/connect-sdk-client-swift/releases/tag/3.2.0). Can you verify that using this version of the SDK no longer causes the App to crash?

**Closed as completed** 2019-03-13 20:21 UTC
